version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10.15-stretch
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build UI components
          command: npm run build

      - run:
          name: Build static version of StoryBook
          command: npm run build-storybook

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    <<: *defaults
    steps:
      - run:
          name: Run static analysis and check code style
          command: npm run lint

      - run:
          name: Run tests
          command: npm run test:jest

  deploy:
    docker:
      - image: xueshanf/awscli:latest

    working_directory: ~/repo

    steps:
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4

      - run:
          name: Deploy to S3
          command:  |
            #export VERSION=${CIRCLE_BRANCH/publish-v/}
            export VERSION=0.0.13
            aws s3 sync public s3://docs.cloudify.co/ui-components/$VERSION --delete --acl public-read storybook-static

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: CY-1485
          requires:
            - test
