version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10.15-stretch
  working_directory: ~/repo

jobs:
  build-test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build application
          command: npm run build

      - run:
          name: Run static analysis and check code style
          command: npm run lint

      - run:
          name: Run tests
          command: npm run test

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test
