def secrets = [
  [path: 'secret/jenkins/github', engineVersion: 2, secretValues: [
    [envVar: 'GITHUB_TOKEN', vaultKey: 'public_token']]],
  [path: 'secret/jenkins/npm', engineVersion: 2, secretValues: [
    [envVar: 'NPM_TOKEN', vaultKey: 'token']]],
]

def configuration = [vaultUrl: "${env.VAULT_URL}",  vaultCredentialId: 'vault-app-role', engineVersion: 2]

def getPublishVersion(String branch){
  return branch.replace('publish-v','')
}

pipeline {
  agent {
    kubernetes {
      label 'components-ui'
      defaultContainer 'jnlp'
      yamlFile 'jenkins/build-pod.yaml'
    }
  }

  environment {
    MAIN_BRANCH = 'master'
    WORKSPACE = "${env.WORKSPACE}"
    BRANCH = "${env.BRANCH_NAME}"
    PROJECT = "cloudify-ui-components"
  }

  options {
    checkoutToSubdirectory('cloudify-ui-components')
    buildDiscarder(logRotator(numToKeepStr:'30'))
    timeout(time: 60, unit: 'MINUTES')
    timestamps()
  }
  stages {
    stage('BUILD') {
      steps {
        sh ""
        container('node'){
          echo "BRANCH: ${env.BRANCH}"
        }
      }
    }
    stage('Publish') {
      when {
        expression { return env.BRANCH =~ /^publish-v.*/ }
      }
      steps {
        container('node'){
          echo "${env.BRANCH}"
        }
      }
    }
  }
}
